import './globals.css'
import { Suspense } from 'react';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google';
import {Navbar} from "../../../components/navbar";
import Loading from './loading';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Admin Page',
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Suspense fallback={<Loading />}>
          <div className="main_content_div">
            {children}
          </div>
        </Suspense>
      </body>
    </html>
  );
};
